### ISSUE TITLE
Table of Content

### ISSUE THREAD

**Issue by adun** [claudioc/jingo#10]
Gollum has an interesting feature: automatic table of content generation.
Usage: ``[[_TOC_]]``
It would be nice to have such feature in Jingo.

Good job so far, great project

**Comment by almereyda** [comment]
@claudioc Check this out, there's an npm module for that : https://github.com/thlorenz/doctoc - maybe it's a quick integration?

**Comment by claudioc** [comment]
#115

**Comment by jpli1221** [comment]
Hi, I just upgraded to version 1.6.0, but still can't see the TOC. Is there any flag that I need to set to enable the TOC feature? Thanks.
