### ISSUE TITLE
deploy to heroku?

### ISSUE THREAD

**Issue by bradoyler** [claudioc/jingo#100]
Is there a workaround for heroku hosting?
I'm getting the `Bad repository path: .` because heroku has an [ephemeral filesystem](https://devcenter.heroku.com/articles/dynos#ephemeral-filesystem)
Hoping there's some way to get the proper path to the local git repo in heroku.
Thanks.

**Comment by bradoyler** [comment]
i have a feeling this is simply not supported on Heroku.

**Comment by OKNoah** [comment]
@bradoyler It's file-based, so like you said deploying to Heroku wouldn't work. However, perhaps it's possible to use a remote git? For example, Github.

**Comment by rj919** [comment]
Here is a workaround:
https://stackoverflow.com/questions/43284285/deploy-jingo-to-heroku/43284286#43284286
