### ISSUE TITLE
validMatches is not working for Github login

### ISSUE THREAD

**Issue by jpli1221** [claudioc/jingo#107]
Using validMatches to restrict user emails is not working.

**Comment by claudioc** [comment]
Is it possible that the user has an empty email?

I've added (as for Jingo 1.5.0) a new `emptyEmailMatches` authorization parameter. Set it to `false` so that the user won't validate.

**Comment by jpli1221** [comment]
Actually, the user has multiple linked emails seems to have problem. User with one email is okay.

**Comment by claudioc** [comment]
Hi,

yes, this problem has already been raised some time ago and there is nothing much I can do. Maybe I should write it down in the README.
