### ISSUE TITLE
systemd jingo wiki

### ISSUE THREAD

**Issue by nzuhdi** [claudioc/jingo#116]
Can someone help me with Jingo + systemd ?

[Service]
ExecStart=/root/.nvm/versions/node/v5.2.0/lib/node_modules/jingo/jingo -c /root/jingo/config.yaml
Restart=always
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=jingo
User=root
Group=root
Environment=NODE_ENV=production

[Install]
WantedBy=multi-user.target

root@testing:/etc/systemd/system# systemctl status jingo
● jingo.service
   Loaded: loaded (/etc/systemd/system/jingo.service; disabled)
   Active: failed (Result: start-limit) since Sat 2015-12-12 12:26:42 EST; 5s ago
  Process: 29518 ExecStart=/root/.nvm/versions/node/v5.2.0/lib/node_modules/jingo/jingo -c /root/jingo/config.yaml (code=exited, status=127)
 Main PID: 29518 (code=exited, status=127)

Dec 12 12:26:41 testing systemd[1]: jingo.service: main process exited, code=exited, status=127/n/a
Dec 12 12:26:41 testing systemd[1]: Unit jingo.service entered failed state.
Dec 12 12:26:42 testing systemd[1]: jingo.service start request repeated too quickly, refusing to start.
Dec 12 12:26:42 testing systemd[1]: Failed to start jingo.service.
Dec 12 12:26:42 testing systemd[1]: Unit jingo.service entered failed state.

**Comment by creynold** [comment]
127 usually indicates the binary wasn't found. Double check your path?

**Comment by nzuhdi** [comment]
You're right. It is because of environment path. Thanks!

Here's my new systemd service with Environment=PATH.

nano /etc/systemd/system/jingo.service

[Unit]
Description=Jingo

[Service]
ExecStart=/root/.nvm/versions/node/v5.2.0/bin/jingo -c /root/config.yaml
Restart=always
User=root
Group=root
Environment=PATH=/root/.nvm/versions/node/v5.2.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Environment=NODE_ENV=production

[Install]
WantedBy=multi-user.target
