### ISSUE TITLE
Current revision not considered up to date

### ISSUE THREAD

**Issue by almereyda** [claudioc/jingo#118]
Despite the footer of http://wiki.transformap.co/wiki/TransforMap/ states it explicitly, when accessed directly via manual composition of the URI, as [the revision history](http://wiki.transformap.co/wiki/TransforMap/history) doesn't create a link to it, http://wiki.transformap.co/wiki/TransforMap/8ad71c0 doesn't believe to be the current version.

> Found when thinking about ways to restrict the used hypothes.is injection on the site only for tagged versions - following the rationale behind inline comments only being possible directly on commits' diffs at GitHub.

**Comment by claudioc** [comment]
Unfortunately this fix adds a `git log` request for each page view.
