### ISSUE TITLE
During authentication process, the user's email is overwritten causing issues with `authorization.validMatches`

### ISSUE THREAD

**Issue by sebastienfilion** [claudioc/jingo#120]
I simply installed Jingo on my server from latest and the line `155` simply overwrite the user's email causing email validation to fail.
```
155: res.locals.user.email = 'jingouser';
```

**Comment by claudioc** [comment]
Oh my god, thank you!

That was a leftover for a test before I released 1.5.2.

Sorry (fixed)!
