### ISSUE TITLE
Project logo

### ISSUE THREAD

**Issue by gramakri** [claudioc/jingo#129]
Just wondering if the jingo project has a logo/icon. There is a public/favicon.ico. Is there a larger version of this?

**Comment by claudioc** [comment]
Yes! Yes! Yes!

This is something definitely and quite urgently missing. I am not a designer myself and I also have not really an idea what kind of "message" to convey with the logo :)

Any idea is greatly appreciated

**Comment by gramakri** [comment]
@claudioc For now, I put a stock icon (https://www.iconfinder.com/icons/173727/wiki_icon#size=128) since I wanted to put your app out there for people to try. As soon as you have an icon, I will be happy to update the app.

**Comment by hajika** [comment]
I would much more like to be able to put my own logo somewhere to the wiki page and as the favicon (ok that might be possible). I like the decend design very much, but it would be easier and nicer to use the wiki If I could add a logo to the title :)

**Comment by claudioc** [comment]
Added in 1.8.2
