### ISSUE TITLE
Demo server down

### ISSUE THREAD

**Issue by jandrieu** [claudioc/jingo#139]
http://jingo.cica.li:6067/wiki/home gives

> This webpage is not available
> 
> ERR_CONNECTION_REFUSED

**Comment by claudioc** [comment]
Hi, thanks for pointing this out but it's working for me.

**Comment by jandrieu** [comment]
Must've been temporary. Or maybe it was the corporate network. I can reach it from home, now. I'll try again at the office just to see if that makes any difference.

**Comment by jandrieu** [comment]
Actually, I think it is because of the abnormal port. My client's IT policies are almost certainly preventing access to port 6067.

You might consider (if possible) an nginx configuration that forwards port 80 to 6067, which would also be great to have documented. That's the setup we are considering--with jingo installed locally rather than globally--and it would be great to have an example.

Anyway, I understand if you close this issue as "won't fix", but it would be great to have the demo on a server at port 80.

**Comment by claudioc** [comment]
Good to know :)

Regarding the documentation about reverse-proxying jingo, you can read something about in [the wiki](https://github.com/claudioc/jingo/wiki)
