### ISSUE TITLE
Bad repository path (not exists) `jingo -c config.yaml ` 

### ISSUE THREAD

**Issue by diegoddox** [claudioc/jingo#147]
I'm getting this error `Bad repository path (not exists):` when I run `jingo -c config.yaml `

This is how I have done.
1: `npm i -g jingo`
2: `clone the repo` and `cd jingo/`
3: `npm i`
4: `jingo -s > config.yaml`
5: `jingo -c config.yaml `

**Comment by claudioc** [comment]
It's the expected result if you don't configure your config.yaml

Please read the appropriate section in the README.md file.

Thanks!

**Comment by wwgc** [comment]
Set the correct repository: 
```
repository: ABSOLUTE_PATH_TO_YOUR_REPO
```
