### ISSUE TITLE
Is there a complete how-to guide for the installation

### ISSUE THREAD

**Issue by kdamianakis** [claudioc/jingo#148]
Hi,

Am a Java developer so don't know much about node.js (yet) but would like to deploy this on a VM - have followed the instructions but am uncertain on any settings to put (for the localhost access) so I can get it running. Is there a default example config to look at or a how-to guide that may provide more details on how to run it? (what default values to put on 'repository' for localhost, for example for a newly created git on the localhost?

Any help will be appreciated.

Regards,
Konstantinos

**Comment by claudioc** [comment]
Hi,

usually the README file should get you started. We have been adding all the possible needed information about the configuration variable.

In your specific case, according to the README, `The repository path must be an absolute path pointing to the root of the repository.`. This means that "repository" must be the absolute directory name of where you ran `git init`.

One of my installations, for examples, uses `repository: "/Users/claudioc/Docrepos/zot.wiki"`

**Comment by sg-s** [comment]
HI @claudioc , this is not clear at all. I too am completely confused by the installation instructions. Can you make a clear, step-by-step installation guide?
