### ISSUE TITLE
how to disable gravator?

### ISSUE THREAD

**Issue by xu4wang** [claudioc/jingo#152]
Just had a fresh installation of jingo, When I log in. Looks like the browser keep trying to load gravatar, The link is:
http://www.gravatar.com/avatar/2326becee316a7a5457d48b19a875415?s=24

However, my network connection is not good to that website and I'd like to disable this feature. Is there any configuration I can use?

Thanks,Xu

**Comment by claudioc** [comment]
No, there is no such option. But It's a good idea to add one. I will take a look into it :)

**Comment by hajika** [comment]
and why you load jquery mini from google? I changed the line with `ajax.googleapis` in layout.pug into `/wiki/vendor/jquery.min.js` and works fine, the jquery.min.js was already there :)

**Comment by claudioc** [comment]
Added in 1.8.2
