### ISSUE TITLE
wrong url for image in the preview page

### ISSUE THREAD

**Issue by xu4wang** [claudioc/jingo#153]
I put a picture in the git repo under assets directory, and put below in the markdown page "sandbox.md" for testing:

```
![payer1](assets/payer1.jpg)
```

The picture is displayed in the sandbox page, and I noticed the piture URL is correct:

```
http://wiki.somedomain.com/wiki/assets/payer1.jpg
```

However, If I preview the sandbox page during editing, the picture is not displayed, and the URL is:

```
http://wiki.somedomain.com/pages/sandbox/assets/payer1.jpg
```

I think there is something wrong during preview?

Thanks, Xu

**Comment by claudioc** [comment]
Thanks, this looks like a bug! I will fix it

**Comment by JSteunou** [comment]
It comes with the fact that you're using relative urls for your image

* in view mode your current location is `/wiki/sandbox` so image will be `/wiki/assets/payer1.jpg`
* in edit mode your current location is `/wiki/sandbox/edit` so image will be `/wiki/sandbox/assets/payer1.jpg`


@claudioc 3 ways to solve this

* force absolute path for images and document it
* trick the xhr response from edit mode to add `../` to all relative urls
* remove `/edit` in edition mode

**Comment by JSteunou** [comment]
@claudioc I edit my first post, I got some paths wrong.

**Comment by claudioc** [comment]
@JSteunou @xu4wang I just wrote a wiki page to describe the problem and the solution :)

Thanks to you both!

https://github.com/claudioc/jingo/wiki/add-images-to-the-Jingo-own-repository
