### ISSUE TITLE
make the page area wider, and make use of the right side of the screen

### ISSUE THREAD

**Issue by xu4wang** [claudioc/jingo#154]
Hello, 

Is there anything I can config to make the page area wider? 

At the moment, the page area is on the middle of the screen, the sidebar is on the left of the page area. On the right of the page area, it's empty.  
Is it configurable to make the page area wider to occupy the right empty area also?

Thanks,
XW

**Comment by claudioc** [comment]
Yes, you can add a custom CSS file (call it `_style.css`) with which you can change basically any style you want (like the content area). Take a look at this PR for inspiration https://github.com/claudioc/jingo/pull/141
