### ISSUE TITLE
Is it possible to run jingo with https?

### ISSUE THREAD

**Issue by joargp** [claudioc/jingo#155]

**Comment by claudioc** [comment]
Yes, but not from Jingo directly (which has not support for reading TLS configurations and start the server in HTTPS). You can run Jingo behind a reverse proxy with https support (like nginx). Take a look at [https://github.com/claudioc/jingo/wiki/Serve-Jingo-pages-behind-a-reverse-proxy].

**Comment by joargp** [comment]
Thanks, totally missed the entry in the wiki (and the wiki itself).
