### ISSUE TITLE
installation problem: Bad repository path (not exists)

### ISSUE THREAD

**Issue by nasser-torabzade** [claudioc/jingo#157]
Hi, I have an installation problem:
I've defined my git remote as `origin`  and it's correctly working.

```
D:\Projects\tests\jingo>git remote show origin
* remote origin
  Fetch URL: http://192.168.1.244/partigaran/myWiki.git
  Push  URL: http://192.168.1.244/partigaran/myWiki.git
  HEAD branch: master
  Remote branch:
    master tracked
  Local branch configured for 'git pull':
    master merges with remote master
  Local ref configured for 'git push':
    master pushes to master (up to date)
```

in my config.yaml I've set application as follows:

```
  repository: 'myWiki'
  docSubdir: ''
  remote: 'origin'
```

when I try to run jingo server, this error shows up:

```
D:\Projects\tests\jingo>jingo -c config.yaml
Bad repository path (not exists): myWiki
```

What am I doing wrong here?
thanks! :)

**Comment by claudioc** [comment]
As stated in the README, the repository path must be an absolute path.

Please also note that Windows is not a well tested (and unsupported) platform for Jingo.

Cheers

**Comment by wwgc** [comment]
Set the correct repository: 
```
repository: ABSOLUTE_PATH_TO_YOUR_REPO
```

**Comment by nikodunk** [comment]
For people coming across this later: This https://github.com/claudioc/jingo/issues/241#issuecomment-410460927 solved the issue for me. The documentation is super unclear on this point.

You need to CLONE your remote repository, and this line "repository" should point to the local clone of your remote repository.
