### ISSUE TITLE
Google Login - failed to obtain token

### ISSUE THREAD

**Issue by thecitysecret** [claudioc/jingo#175]
Hi,

Bit unsure on this error had a google around but still no closer to solving it. When I try to login to the Wiki via Google it comes up with this error

failed to obtain access token (Error: getaddrinfo ENOTFOUND accounts.google.com accounts.google.com:443)

**Comment by claudioc** [comment]
Hi,

since ENOTFOUND ("Error: not found") is related to `accounts.google.com` this is not a problem with Jingo.
