### ISSUE TITLE
Filename save in Chinese can not be listed in Chinese

### ISSUE THREAD

**Issue by choicky** [claudioc/jingo#181]
For example, I created a new wiki page named `专利法-2008年公布版` in Chinese.  The page is correctly saved.  

However, it's listed as `\344\270\223\345\210\251\346\263\225 2008\345\271\264\345\205\254\345\270\203\347\211\210.md` in the `all pages` .  

The link is also linked to `~/\344\270\223\345\210\251\346\263\225 2008\345\271\264\345\205\254\345\270\203\347\211\210.md` which is not found.

If I manually replace the link with `专利法-2008年公布版` the newly created wiki page is correctly shown.

**Comment by claudioc** [comment]
Hi @choicky,

I will take a look at this issue

thanks for reporting

**Comment by 9n** [comment]
@choicky try `git config --global core.quotepath false` to fix this.

**Comment by claudioc** [comment]
@choicky did @9n suggestion fix the problem?

**Comment by xhj967** [comment]
i want to classify the page as the treeviw list,can someone offer me a detail tutorial.
thanks
