### ISSUE TITLE
Run jingo public with ssl support

### ISSUE THREAD

**Issue by swilkTUDA** [claudioc/jingo#196]
Is it possible to provide a jingo wiki over https?

**Comment by claudioc** [comment]
Yes, of cource. The jingo server doesn't support TLS termination, but it'd be very easy to setup an nginx server in front of it using a certificate from Let's encrypt, for example.

There is a page in the wiki explaining how to put Jingo behind nginx: https://github.com/claudioc/jingo/wiki/Serve-Jingo-pages-behind-a-reverse-proxy
