### ISSUE TITLE
Preferred way to have jingo run at startup, unattended?

### ISSUE THREAD

**Issue by concentrateddon** [claudioc/jingo#200]
Is there a preferred way for having jingo start up, unattended, when the server boots?

**Comment by concentrateddon** [comment]
As a note, here's what I've come up with.

I'm using the pm2 Node.js module:

```
pm2 startup
pm2 start jingo -- -c /path/to/config.yaml
```

This gets Jingo running at server boot. The leaves the problem of letting Jingo access GitHub automatically. Because our server is fairly locked-down, we've chosen to use an un-password-protected private SSH key file. This lets us add the key file location to ~/.ssh/config, so that Git can find the SSH key automatically. It's been working smoothly.

**Comment by claudioc** [comment]
Thanks @concentrateddon for the hint. I indeed use pm2 myself (not only for Jingo but for all my node projects too).

If someone is reading this, take a moment to read the awesome introduction to pm2 from Digitalocean (their tutorials are always fantastic) https://www.digitalocean.com/community/tutorials/how-to-use-pm2-to-setup-a-node-js-production-environment-on-an-ubuntu-vps
