### ISSUE TITLE
Broken demo link

### ISSUE THREAD

**Issue by jcpayne** [claudioc/jingo#203]
In the Readme file, it says:
"There is a demo server running at http://jingo.cica.li:6067/wiki/home", but the link seems to be broken.
It would be nice to list some example websites if available.

**Comment by mariusv** [comment]
If is needed I can easily put a demo up on my server. Actually I would be more than happy to do it as long as you guys are ok with it.

On May 13, 2017 1:19:41 AM GMT+01:00, John Payne <notifications@github.com> wrote:
>In the Readme file, it says:
>"There is a demo server running at
>http://jingo.cica.li:6067/wiki/home", but the link seems to be broken.
>It would be nice to list some example websites if available.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/claudioc/jingo/issues/203

-- 
Sent from my mobile device. Please excuse my brevity.

**Comment by claudioc** [comment]
@jcpayne @mariusv thank you, guys! I think I definitely fixed the issue moving the demo server for a crappy hosting provider (CloudAtCost) to a more reasonable one (Vultr).

Now The demo is up and running! http://jingo.cica.li/wiki/home

**Comment by jcpayne** [comment]
Thank you Claudio, that page looks very nice.  I really like the typesetting and the clean layout.  Questions: 1) I don’t see any options to edit pages.  Is it necessary to log in before the tools become visible?   2) The only authentication option that pops up on the login menu is Google+ but I don’t have a Google+ account (by choice).  Is it possible to add other options if I host my own wiki?  It would be nice if the demo included an example of other authentication options.

 

Cheers,

 

John
