### ISSUE TITLE
\| in tables is still interpreted

### ISSUE THREAD

**Issue by hajika** [claudioc/jingo#215]
I tried to print out a | in a table context, but it looks like it is not possible to escape it with \\|. Is there any other way?

Putting it in backticks (like \`[link | link.com]\`) returns the actual html link container, thats awkward :)

similar problem with ordered lists, `\1`. is not interpreted, but the `\` is returned on the page

**Comment by claudioc** [comment]
Apparently there is no way (the markdown parser is not under my full "control". It's the `marked` module. Someone suggested to move to use another parser (#187) which may or may not "fix" the issue but it'll be a lot of work and I'll probably move this idea to the next jingo major version

**Comment by franklinyu** [comment]
This is fixed in [Marked v0.4.0](https://github.com/markedjs/marked/releases/tag/0.4.0), but anyway Markdown-it does not have this issue at all.

**Comment by claudioc** [comment]
good to know! Thanks (the new Jingo is (will be) using Markdown-it indeed...)
