### ISSUE TITLE
Header IDs interfere with jingo

### ISSUE THREAD

**Issue by mjflan** [claudioc/jingo#234]
If I add a document header:
```html
### login
```
...to my document then the toolbar goes away. At that point, I have to edit the file externally to fix it by changing the header name.

I think this is an exception in the Jingo javascript in the browser, but a brief review shows that there are element IDs that are easily duplicated by users that interfere with jingo's functionality. I would suggest replacing built-in element IDs with stylized names like `_jingo_login` or something of that sort. It would make it much more difficult for regular users (like me) to bump into them and break the wiki.

**Comment by claudioc** [comment]
Ouch, you're right.

Let me fix this :)
