### ISSUE TITLE
Bad repository path (not exists)

### ISSUE THREAD

**Issue by physiii** [claudioc/jingo#241]
I clone the repo, created config.yaml (./jingo -s > config.yaml)

changed the repo to one I know exists (https://github.com/physiii/jingorepo)

But still getting the error:
Bad repository path (not exists): https://github.com/physiii/jingorepo

config.yaml:

$ cat config.yaml
---

> # Configuration sample file for Jingo (YAML)
> application:
>   title: Jingo
>   logo: ''
>   favicon: ''
>   repository: 'https://github.com/physiii/jingorepo'
>   docSubdir: ''
>   remote: 'origin'
>   pushInterval: 30
>   secret: chnge_me
>   git: git
>   skipGitCheck: false
>   loggingMode: 1
>   pedanticMarkdown: true
>   gfmBreaks: true
>   staticWhitelist: '/\.png$/i, /\.jpg$/i, /\.gif$/i'
>   proxyPath: ''
> authentication:
>   google:
>     enabled: true
>     clientId: replace me with the real value
>     clientSecret: replace me with the real value
>     redirectURL: ''
>   github:
>     enabled: false
>     clientId: replace me with the real value
>     clientSecret: replace me with the real value
>     redirectURL: ''
>   ldap:
>     enabled: false
>     url: 'ldap://example.org:389'
>     bindDn: ''
>     bindCredentials: ''
>     searchBase: 'ou=people,dc=example,dc=org'
>     searchFilter: '(uid={{username}})'
>     searchAttributes: ''
>   local:
>     enabled: false
>     accounts:
>       - username: ''
>         passwordHash: ''
>         email: ''
> features:
>   markitup: false
>   codemirror: true
>   gravatar: true
> server:
>   hostname: localhost
>   port: 6067
>   localOnly: false
>   baseUrl: ''
>   CORS:
>     enabled: false
>     allowedOrigin: '*'
> authorization:
>   anonRead: true
>   validMatches: .+
>   emptyEmailMatches: false
> pages:
>   index: Home
>   title:
>     fromFilename: true
>     fromContent: false
>     asciiOnly: false
>     lowercase: false
>   itemsPerPage: 10
> customizations:
>   sidebar: _sidebar.md
>   footer: _footer.md
>   style: _style.css
>   script: _script.js
>

**Comment by claudioc** [comment]
As mentioned in the README, the `repository` must be a `Absolute path for your documents repository (mandatory).`. It's a local repository (a checkout of your remote, probably), not a remote repository.
