### ISSUE TITLE
why does it wrap paragraphs within blockquotes in quotes?

### ISSUE THREAD

**Issue by bwl21** [claudioc/jingo#256]
the following 

```markdown
> **Hint**: why is
> this paragraph in quotes
>
> * list in blockquote
>
> and another paragraph
```

yields

![screenshot_1306](https://user-images.githubusercontent.com/2022976/51801593-40af6a80-2240-11e9-9348-0ff62530381a.jpg)

I wonder why the paragraphs in the blockquote are wrapped in quotes.

**Comment by bwl21** [comment]
I saw it is a matter of styling ...

**Comment by claudioc** [comment]
I think you can easily turn this behaviour off
