### ISSUE TITLE
Running with pm2 on Windows produces lots of popup windows

### ISSUE THREAD

**Issue by mavjt** [claudioc/jingo#257]
I can run the site using the normal command: node jingo -c newconfig.yaml

But if I try to run with pm2: pm2 start etc\pm2.json
the site runs fine, but each time I visit or save a page, I see lots of windows command windows appear and disappear.  They look to be running git commands.  I recorded it and attach here
[jingo.zip](https://github.com/claudioc/jingo/files/2916993/jingo.zip)

**Comment by mavjt** [comment]
If anyone has another way of running Jingo on a windows box let me know please

**Comment by claudioc** [comment]
Hi Mark,

unfortunately, I don't have time to support Windows for Jingo.
