### ISSUE TITLE
NTLM auth

### ISSUE THREAD

**Issue by dmitriym09** [claudioc/jingo#260]
I want to add [NTLN auth](https://www.npmjs.com/package/passport-ad) in jingo. It`s need for me. Can I pushing result in main repo? Or better to fork and keep my separate repository?

**Comment by claudioc** [comment]
Hey @dmitriym09,

thank you for proposing to include your change in Jingo; if you want you can submit a PR for other people to use in case they need it, but at the moment I am not accepting any other big change in Jingo 1

Thanks!
