### ISSUE TITLE
page name with colon cause search result wrong

### ISSUE THREAD

**Issue by GHolk** [claudioc/jingo#263]
i am trying to use colon or slash as namespace sepatator.
the slash `/` is replaced by `+` on filesystem, and colon is keeped,
but in search result, the filename after colon is interpreted as line number
from the result of `git grep` (in `lib/gitmech.js`) .
thus render wrong result.

**Comment by claudioc** [comment]
Hey @GHolk can you please give me an example of some page names that show this behaviour? Thanks!

**Comment by GHolk** [comment]
the page with colon in name:
https://lab.gholk.ml/jingo/wiki/test:name-with-colon

display wrong in search result:
https://lab.gholk.ml/jingo/search?term=name-with-colon

**Comment by claudioc** [comment]
Thank you, fixed (check the commit to see how, if you want) :D
