### ISSUE TITLE
Demo server is down

### ISSUE THREAD

**Issue by ninjavic** [claudioc/jingo#29]
Can't find demo of jingo ((( I tried a demo server running from example - 

http://jingo.cicali.cc:6067/wiki/home

**Comment by Memphizzz** [comment]
Down again?

**Comment by claudioc** [comment]
Thanks for reporting! I changed server this weekend and probably something went wrong.

btw, now we can also access the demo directly from `jingo.cica.li` :D

**Comment by aurabindo** [comment]
Both [jingo.cica.li:6067/wiki/home] and [jingo.cica.li] are not connecting. Down again I suppose?

**Comment by claudioc** [comment]
Thank you @aurabindo 

This is just a reminder that nobody should buy stuff from Cloudatcost

I will restart it when I got control back from those servers 👍

**Comment by aurabindo** [comment]
@claudioc I'm pretty happy with Scaleway. No issues yet. Using it for about 6 months.
