### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by almereyda** [claudioc/jingo#68]
The current implementation of Tables does not work exaclty.

Also the document's CSS could be improved for clarity.

**Comment by claudioc** [comment]
Hi,

what to you mean my "improve the document CSS"?

**Comment by scordature** [comment]
This should appear as a table, correct?

```
foo | bar
----| ----
syn | ack
one | two
```

In my test page it does not appear as a table.

The backticks above are just for clarity. I don't use them in my test page.

http://jingo.cica.li:6067/wiki/And-we-will-all-the-pleasures-prove

**Comment by claudioc** [comment]
For sure what was missing was the CSS support to tables (oops). But the markdown support was there already (from marked). It just seems tables are very sensitive on how you create them with markup.

https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables

**Comment by scordature** [comment]
thanks, Claudio, this is great!
