### ISSUE TITLE
Passport does not work under Nginx Reverse-proxy

### ISSUE THREAD

**Issue by sebglon** [claudioc/jingo#72]
The Google Oauth does not work under a reverse-proxy.
I think you are missing the next module passport-reverserproxy.

Is it possible to add this?

Thanks

**Comment by claudioc** [comment]
Hi,

oh, I didn't test it to be honest. I will and try to fix it. Thanks for reporting the issue!

**Comment by claudioc** [comment]
Can you tell me which kind of reverse proxy are you using? It would be fantastic if could also provide the configuration :)

**Comment by claudioc** [comment]
I just tried using nginx and proxing requests to jingo, and it works. My configuration follows:

```
daemon off;
error_log /dev/stdout info;

events {
    worker_connections  1024;
}

http {
    server {
        listen 2222;

        server_name jingo.dev;

        location / {
            proxy_pass http://127.0.0.1:6067;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }
    }
}
```

**Comment by sebglon** [comment]
Yes but My proxy is on another server.
and All the server jingo is not directy accessible on web.

**Comment by sebglon** [comment]
This issue can be closed;
my server had no internet access.
After changing this, all is OK
