### ISSUE TITLE
Most documents not found after upgrading to current

### ISSUE THREAD

**Issue by StevenLangbroek** [claudioc/jingo#73]
Hey Claudio,

We just upgraded to current version (because OpenID :/ ) after reading your note about compatibility with 0.6 range. The system works, but most documents we link to are "non existent". I can see the markdown files in the appropriate folders, the pages just aren't generated. For example, `pages/General-Knowledge` doesn't work, but `BrandEngage (Database Schema)` does work... Any idea what would cause this behavior? I inspected the Markdown files, but don't see anything specific about the files that would warrant this. They all have appropriate headers, they're all in the same folder...

Thanks!

- Steven

**Comment by claudioc** [comment]
It can be a git related issue. Jingo does not use the file system to get to the file (only when it needs the actual content), but uses git instead. Take a look of your git repo and ensure that everything is in the right place (maybe there are some not committed changes?).

Also, it can be a problem with the name of the files: take a look at the documentation of the `pages.title` subkeys
