### ISSUE TITLE
LDAP authentication

### ISSUE THREAD

**Issue by frdmn** [claudioc/jingo#81]
I would love to use jingo as documentation platform in my team, however we would need LDAP support for authentication first.

Any plans to add it?

**Comment by claudioc** [comment]
Hi, no at the moment I am not planning any further enhancement for the authentication subsystem. The problem is that Jingo is thought to be small and doesn't have a plugin system. Adding more authentications methods (or renderers, or themes...) would make it less stable and hard to test. Sorry!
