### ISSUE TITLE
Defining remote throws an error: Remote does not exist

### ISSUE THREAD

**Issue by reybango** [claudioc/jingo#91]
Hey guys, I'm getting a "Unhandled rejection Error: Remote does not exist (git://git@github.com:reybango/jingotest.git)" message. That's the valid remote declaration from Github and it's set properly since I can push manually from my machine.

In config.yaml I defined remote as:
remote: 'git://git@github.com:reybango/jingotest.git'

and I've tried the following variations too:
remote: 'git@github.com:reybango/jingotest.git'
remote: 'https://github.com/reybango/jingotest.git'

It's probably something very simple but the docs didn't quite define how to do it. If you can give me some guidance I'd be happy to do a pull request to update the docs with it once I get this fixed.

**Comment by claudioc** [comment]
Hi,

the `remote` configuration directive is the name of the remote that you have defined to your _local_ repository with a `git remote add remotename remoteaddress`. Jingo cannot create a remote for you.

So, to be able to use a remote with Jingo, just add a local remote and use that name in the `remote` key of the config.

Hope this help!

**Comment by reybango** [comment]
Hey @claudioc, thanks for the reply. I understand that Jingo won't do that. When I created my Github repo (https://github.com/reybango/jingotest), I added the remote to my local machine and that's working. That was done using Github's:

'git remote add origin https://github.com/reybango/jingotest.git'

Hence why when I do a 'git push' manually, my Github repo is updated.

It's just not working via Jingo when I define the remote in the 'remote' property in config.yaml.

**Comment by claudioc** [comment]
As I said, try using:
```
remote: origin
```

It should work then.

**Comment by reybango** [comment]
Yep that did it. Thanks! PR coming shortly.

**Comment by cdslashetc** [comment]
Oh, it's the remote _name_ not the URL! Perhaps that could be clearer in the documentation somehow?

I thought there was a problem with BitBucket and set up GitPrep then Gogs trying to find something that worked.

**Comment by claudioc** [comment]
Well, the documentation actually states `This is the name of the remote you want to push/pull to/from (optional)`. Whenever a `remote` is mentioned, it is mentioned that this is the name of the remote, not the URL :)
