### ISSUE TITLE
CodeMirror should use gfm mode

### ISSUE THREAD

**Issue by ryanvarick** [claudioc/jingo#99]
Jingo uses Github-flavored Markdown but the default CodeMirror setting is plain Markdown. I tried to change the mode in the template, but it didn't work. Not sure how to enable [gfm mode](http://codemirror.net/mode/gfm/).

**Comment by claudioc** [comment]
Interesting. Seems like the `gfm` mode is not distributed with codemirror, but exists as a separate module. Let's see if I can install that. Thanks :)

**Comment by claudioc** [comment]
no, my fault. The codemirror bundled with Jingo does not include gfm. Going to fix it.
